### ISSUE TITLE
Add # of watches and # of stars to tweet

### ISSUE THREAD

**Issue by superbilk** [andygrunwald/TrendingGithub#6]
As long as you are <140 chars, add useful information like number of watches, number of stars, delta of these, etc

**Comment by andygrunwald** [comment]
THX @superbilk! For reference: Our chat on twitter -> https://twitter.com/superbilk/status/635527011734298625

What do you think is your priority of information? 140 chars are very limited.
Currently it is (see https://github.com/andygrunwald/TrendingGithub/blob/master/tweets.go#L141):

1. Name of Repository
1. Description (minimum 20 chars)
1. URL
1. Hashtag for language

Should we drop the hastag for the language in favor of the stars?

**Comment by mre** [comment]
I personally find the hashtag for the language very helpful. It helps me decide if the project is of general interest to me. Other than that the number of stars is a good quantifier of "maturity", so it makes sense to add this if there's enough space. The format could be something like [12 stars] maybe?

**Comment by andygrunwald** [comment]
Or instead of wasting 5 chars ("stars"), we can try to use an emojy like :star: (we have to see how many chars twitter will get rid of ;))

**Comment by superbilk** [comment]
personally I would prefer

1. Description
2. Name of Repository
3. optional: stars, watches, maturity
4. URL
5. Hashtag for language

Format for stars could be ★134
Maybe you could drop the repository owner and just use the name of the project.
Try to shorten the URL as much as possible
And keep the hastag for language, that way i can mute obscure languages and see if I'm interested at all

**Comment by mre** [comment]
Sounds good, @superbilk

**Comment by andygrunwald** [comment]
Good input! Thx!
> Try to shorten the URL as much as possible
Twitter got it`s own url shortener. "t.co". Currently it is ~22 chars long. See https://dev.twitter.com/overview/t.co
Maybe i can find a shorter one. We will see, because this would be an additional API usage (can fail as well, etc.) and so on.
I think we should continue t.co for the next time.

**Comment by andygrunwald** [comment]
Note for myself:
Getting the stars of a repository needs an http call to https://api.github.com/repos/google/go-github (for google/go-github) and receive the stargazers_count field.

**Comment by andygrunwald** [comment]
I added the number of stars to the tweet if this will fit.
The number of watches was dropped, because i think stars are more useful metric.

I will continue on improving the way how to build a tweet.
E.g. 
* if the name of the owner is the same as the project (docker, etcd, etc.) i will drop the name of the owner.
* if the name of the owner is to long to drop stars and hashtag i will drop the name of the owner
* etc.

I will release and deploy a new version tomorrow.

THX for your contribution.
